CREATE TABLE IF NOT EXISTS media_objects (key TEXT PRIMARY KEY, mime TEXT NOT NULL, bytes INTEGER NOT NULL, complete INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS media_chunks (key TEXT NOT NULL REFERENCES media_objects(key) ON DELETE CASCADE, position INTEGER NOT NULL, data BLOB NOT NULL, PRIMARY KEY(key,position));
